### PR TITLE
Initial Carousel

### PR DESCRIPTION
**Pull request by cjgammon**
Add carousel functionality.

## URL for testing:

- https://carouselgsap--design-website--adobe.hlx3.page/

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by pfulton — CHANGES_REQUESTED** [review]
Things are looking awesome, @cjgammon! Great work.

A few things:
1. We should send the preview URL to Joslyn so he can take a look at things (once you're fully ready).
2. For the "tablet" size (right now that's between `900px` and `1300px`, Joslyn's design moves the navigation buttons to a spot that's below the text in each slide. (see the attachment below). Would you mind taking a shot at repositioning the buttons between those breakpoints?
3. I'm not sure about the PageSpeed failures here. I'm guessing it's because of us bringing in GSAP. What options do we have for handling 3rd party libraries + appeasing PageSpeed, @davidnuescheler? Is it better for us to serve up those assets? Or should we use a CDN? (I have yet to come across using a CDN with 3rd party assets while at Adobe, so you may need to advise on best practices there)

**Comment by cjgammon** [comment]
@pfulton I adjusted the layout on tablet so the buttons are under the image.

**Comment by davidnuescheler** [comment]
yeah, the LH score is likely impacted by GSAP blocking the load of the LCP element, which is the first slide.
so generally we just need to get to a display some placeholder logic until GSAP and the rest of carousel is loaded, i will give it whirl and try to propose something in this branch if that's ok...

**Comment by davidnuescheler** [comment]
so i got everything under control other than the `TBT`... it looks like a lot of the time is attributed to "rendering"... which usually means that there either animation frame requests that happen too early (which i thought i suppressed by pushing the loading of the carousel back to 4s delay) or maybe it is some crazy css rules, which i can't see immediately.
the issue is really that the local testing of `TBT` yields completely different results (eg. TBT of 0), so this may also be a PSI anomaly (those are not very frequent though). 
i will try more later...

**Review by pfulton — APPROVED** [review]
This looks awesome @cjgammon - great work.

**Pull request merged**
