### PR TITLE
add scroll down indicator and adjust animation / height of carousel 

### PR DESCRIPTION
**Pull request by cjgammon**
A couple minor changes to carousel behavior/layout
- https://feat--scrolldown--design-website--adobe.hlx3.page/

### CODE REVIEW

**Comment by cjgammon** [comment]
Now includes the removal of gsap in project, favoring CDN

**Review by pfulton — APPROVED** [review]
I think we're good to go here. Thanks for changing up the GSAP library stuff @cjgammon - I appreciate it.

I see that the Lighthouse score is lower - this is something we'll want to keep an eye on and/or work on separately, I think.

**Comment by cjgammon** [comment]
We can keep an eye on it.  The TBT has been hard to pin down exactly.

**Comment by davidnuescheler** [comment]
yeah, i will look at the `TBT` historically that has never been an issue unless people used large libraries... 
the `SI` of 2.6s though is also not stellar, and i am not quite sure where that's from...

**Pull request merged**
